api/urls.py
from django.urls import path
from rest_framework_simplejwt import views as jwt_views

from api import views

app_name = 'api'

urlpatterns = [
    # Your URLs...
    path('token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('firebasetoken/', views.FirebaseTokenObtainPairView.as_view(), name='firebase_token_obtain_pair'),
    path('token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    path('test', views.HelloView.as_view(), name="hello"),
]

base/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import TemplateView

app_name = "base"

urlpatterns = [

    path('', views.index, name='index'),
    path('clubs/', views.club_home, name='all_clubs'),
    path('clubs/<slug:club_name_slug>/request-join/', views.request_join, name='club_request_join'),
    path('clubs/<slug:club_name_slug>/follow/', views.follow_club, name='club_follow'),
    path('clubs/<slug:club_name_slug>/unfollow/', views.unfollow_club, name='club_unfollow'),

    path('clubs/<slug:club_name_slug>/admin/settings/', views.club_settings, name='club_settings'),
    path('clubs/<slug:club_name_slug>/admin/members/', views.member_list, name='member_list'),
    path('clubs/<slug:club_name_slug>/admin/moderators/', views.moderator_list, name='moderator_list'),
    path('clubs/<slug:club_name_slug>/admin/pending_posts/', views.pending_posts_list, name='pending_posts_list'),
    path('clubs/<slug:club_name_slug>/admin/groups/', views.club_groups, name='club_groups'),

    path('clubs/<slug:club_name_slug>/members/add/', views.add_member, name='add_member_name_as_param'),
    path('clubs/<slug:club_name_slug>/members/add/<str:username>/', views.add_member, name='add_member'),
    path('clubs/<slug:club_name_slug>/members/remove/<str:username>/', views.remove_member, name='remove_member'),
    path('clubs/<slug:club_name_slug>/members/approve/<str:username>/', views.approve_member, name='approve_member'),

    path('clubs/<slug:club_name_slug>/moderators/add/', views.add_moderator, name='add_moderator_name_as_param'),
    path('clubs/<slug:club_name_slug>/moderators/add/<str:username>/', views.add_moderator, name='add_moderator'),
    path('clubs/<slug:club_name_slug>/moderators/remove/', views.remove_moderator,
         name='remove_moderator_name_as_param'),
    path('clubs/<slug:club_name_slug>/moderators/remove/<str:username>/', views.remove_moderator,
         name='remove_moderator'),

    path('clubs/<slug:club_name_slug>/posts/approve/<int:encrypted_id>/', views.approve_post, name="approve_post"),
    path('clubs/<slug:club_name_slug>/posts/reject/<int:encrypted_id>/', views.reject_post, name="reject_post"),

    path('notifications', views.NotificationView.as_view(), name='notifications'),

    path('post_email_temp', views.post_email_temp)

]

club_portal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from base import views as base_views

urlpatterns = [
    path('api/', include("api.urls")),
    path('admin/', admin.site.urls),
    path('registration/', include("registration.urls")),
    path('accounts/', include("accounts.urls")),
    path('posts/', include("posts.urls")),
    # path('', base_views.IndexView.as_view(), name="index"),
    path('', include("base.urls")),
    path('ckeditor/', include("ckeditor_uploader.urls")),
    path('', include('django.contrib.auth.urls')),
    path('random-useless-path/', include("posts.urls")),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from django.contrib.auth.views import TemplateView
from . import views

app_name = "posts"

urlpatterns = [
    path('like_post/<int:id>/', views.likePost, name='like-post'),

    path('events/', views.events, name="events"),
    path('polls/', views.polls, name="polls"),
    path('like_post/<int:id>/', views.likePost, name='like-post'),
    path('edit-post/<int:encrypted_id>/', views.edit_post, name="post-edit"),
    path('edit-poll/<int:encrypted_id>/', views.edit_poll, name="poll-edit"),
    path('edit-event/<int:encrypted_id>', views.events_edit, name="events_edit"),
    # path('add-user-event-interested', views.interested_event)
    path('<slug:club_name_slug>/create-poll/', views.create_poll, name='create_poll'),
    # path('<slug:club_name_slug>/submit-poll/', views.submitPoll, name='submit_poll'),
    path('<slug:club_name_slug>/', views.club_posts, name="club_posts"),
    path('<slug:club_name_slug>/events/', views.club_events, name="club_events"),
    path('<slug:club_name_slug>/polls/', views.club_polls, name="club_polls"),
    path('<slug:club_name_slug>/<int:encrypted_id>', views.post_detail, name="post_detail"),
    path('<slug:club_name_slug>/create', views.create_post, name="post-add"),

    path('<slug:club_name_slug>/<int:encrypted_id>/issue-update', views.post_update, name="post-update"),

    path('<slug:club_name_slug>/<int:encrypted_id>/vote', views.cast_vote, name='cast-vote'),
    path('<slug:club_name_slug>/<int:encrypted_id>/subscribe', views.subscribe, name='subscribe'),
    path('<slug:club_name_slug>/<int:encrypted_id>/unsubscribe', views.unsubscribe, name='unsubscribe'),
    path('<slug:club_name_slug>/<int:encrypted_id>/event_interested', views.event_interested, name='event_interested'),
    path('<slug:club_name_slug>/<int:encrypted_id>/event_not_interested', views.event_uninterested,
         name='event_uninterested'),

    path('<slug:club_name_slug>/events/create', views.events_create, name="events_create"),

    # path('ajax/interested_event', views.interested_event, name="interested_event"),

    path('<slug:club_name_slug>/<int:encrypted_id>/pin', views.pin_post, name="pin-post"),
    path('<slug:club_name_slug>/<int:encrypted_id>/unpin', views.unpin_post, name="unpin-post"),
    path('', views.posts, name='posts'),

]

registration/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views
from registration import views

from . import views

app_name = "registration"


urlpatterns = [


    path('signup/', views.signup,name='signup'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('google-login', views.google_signin, name="google_signin"),

    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('choose-club', views.choose_club, name="choose-club")
]

base/models.py
import os

from django.core.exceptions import ValidationError
from django.db import models, IntegrityError, transaction
from django.contrib.auth.models import User

# Create your models here.
from django.db.models import signals, ProtectedError
from django.dispatch import receiver


def club_name_validator(name):
    if '-' in name:
        raise ValidationError('The name can not contain \'-\'')


def club_logo_upload(instance, filename):
    return os.path.join('clubs', instance.name.replace(' ', '_'), filename)



class Club(models.Model):
    name = models.CharField(max_length=100, validators=[club_name_validator], db_index=True)
    full_name = models.CharField(max_length=100)
    date_formed = models.DateField(auto_now_add=True)
    email = models.EmailField(null=True, blank=True)
    about = models.TextField(help_text="Say a few lines about your club", null=True, blank=True, max_length=500)
    is_active = models.BooleanField(default=True)
    is_supported = models.BooleanField(default=True)
    # num_users = models.IntegerField(default=0)

    back_img = models.ImageField(upload_to=club_logo_upload, blank=True, null=True)

    def __str__(self):
        return self.name

    @property
    def slug(self):
        return self.name.replace(' ', '-')

    def calc_users(self):
        self.num_users = self.clubmember_set.all().count()
        self.save()

    class Meta:
        ordering = ['name']


class ClubSettings(models.Model):
    club = models.OneToOneField(to=Club, on_delete=models.CASCADE)


class ClubMentor(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.PROTECT)
    club = models.ForeignKey(Club, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.club.name + " - " + self.user.username

    class Meta:
        unique_together = ('user', 'club')

    def __str__(self):
        return self.club.name + "-" + self.user.username    


class ClubPresident(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    # We can't allow user to be deleted unless new president is set
    club = models.OneToOneField(Club, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.club.name + "-" + self.user.username

    class Meta:
        unique_together = ('user', 'club')


class ClubModerator(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    club = models.ForeignKey(Club, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.user.username + ' moderator')

    class Meta:
        unique_together = ('user', 'club')

    def __str__(self):
        return self.club.name + "-" + self.user.username
        
class ClubMember(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    club = models.ForeignKey(Club, on_delete=models.CASCADE)
    is_approved = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username + '-' + self.club.name

    class Meta:
        unique_together = ('user', 'club')


class Notification(models.Model):
    sender = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="sentNotifications")
    club = models.ForeignKey(Club, on_delete=models.CASCADE, null=True, blank=True)
    # is_read = models.BooleanField(default=False, null=False)
    receivers = models.ManyToManyField(
        User, related_name="receivedNotifications", blank=True)

    title = models.TextField()
    message = models.TextField()

    sent_at = models.DateTimeField(auto_now_add=True)


class EmailProvider(models.Model):
    name = models.TextField()

    current = models.IntegerField(default=0)
    limit = models.IntegerField(null=False)

    # in days, when to reset the current count
    reset = models.IntegerField()

    last_reset = models.DateTimeField(auto_now_add=True)


# @receiver(signals.post_save, sender=Club)
# def random_back_image(sender, instance, created, **kwargs):
#     if created:
#
#         if not hasattr(instance.back_img,'url'):
#             pass

@receiver(signals.post_save, sender=ClubMember)
def member_follow_club(sender, instance, created, **kwargs):
    # If a user is made a moderator, also make him a member of the club
    try:
        instance.user.userprofile.following_clubs.add(instance.club)
    except IntegrityError:
        # User is already a member. Do Nothing
        pass


@receiver(signals.post_save, sender=ClubModerator)
def moderator_add_member(sender, instance, created, **kwargs):
    # If a user is made a moderator, also make him a member of the club
    try:
        with transaction.atomic():  # We need to make atomic as code may throw integrity error
            ClubMember.objects.create(user=instance.user, club=instance.club, is_approved=True)
    except IntegrityError:
        # User is already a member. Do Nothing
        pass


@receiver(signals.post_save, sender=ClubPresident)
def president_add_moderator_member(sender, instance, created, **kwargs):
    # If a user is made a president, also make him a member and moderator of the club
    try:
        with transaction.atomic():  # We need to make atomic as code may throw integrity error
            ClubModerator.objects.create(user=instance.user, club=instance.club)
        # Just making moderator is enough, as while making moderator, the above signal will be called, which will make him a member
    except IntegrityError:
        # User is already a moderator. Do Nothing
        pass


@receiver(signals.post_save, sender=ClubMentor)
def mentor_add_moderator(sender, instance, created, **kwargs):
    try:
        with transaction.atomic():
            ClubModerator.objects.create(user=instance.user, club=instance.club)
    except IntegrityError:
        # User is already a moderator. Do Nothing
        pass


@receiver(signals.pre_delete, sender=ClubModerator)
def moderator_delete_protect_president(sender, instance, **kwargs):
    # If a moderator is deleted, and if user is also president, prevent delete of moderator
    if instance.club.clubpresident.user == instance.user:
        raise ProtectedError("Can not delete moderator who is also president", instance)


@receiver(signals.pre_delete, sender=ClubMember)
def member_delete_moderator(sender, instance, **kwargs):
    # If a member is deleted, also delete moderator

    mod_instance = ClubModerator.objects.filter(user=instance.user, club=instance.club)
    if mod_instance.exists():
        mod_instance.delete()

base/forms.py
from django import forms
from .models import Club


class ClubForm(forms.ModelForm):
    class Meta:
        model = Club
        fields = ['name', 'full_name', 'email', 'about', 'back_img']

base/templates/base/club/admin_base.html
{% load static %}
{% load club_user_filters %}
<!DOCTYPE HTML>
<html>
<head>
    <title>
        {% block title %}
            Club Admin
        {% endblock %}
    </title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no"/>
    <link rel="stylesheet" href="{% static 'admin_panel/css/admin_panel.css' %}"/>
    {% block custom_head %}
    {% endblock %}
</head>

<body class="is-preload">
<div id="wrapper">
    <!-- Main -->
    <div id="main">
        <div class="inner">
            <!-- Section -->
            {% block main_content %}

            {% endblock %}

        </div>
    </div>

    {% block main_sidebar %}
        <!-- Sidebar -->
        <div id="sidebar">
            <div class="inner" style="position:relative; height: 90vh;">
                <nav id="menu">
                    <header class="major">
                        <h2>{{ club.name|title }} Admin</h2>
                    </header>
                    <ul>
                        <li><a href="{% url 'base:club_settings' club_name_slug %}">General</a></li>
                        <li><a href="{% url 'base:member_list' club_name_slug %}">Members</a></li>
                        {% if request.user == club.clubpresident.user or request.user|is_user_mentor:club %}
                        <li><a href="{% url 'base:moderator_list' club_name_slug %}">Moderators</a></li>
                        {% endif %}
                        <li><a href="{% url 'base:pending_posts_list' club_name_slug %}">Posts</a></li>
                        <li><a href="{% url 'base:club_groups' club_name_slug %}">Groups</a></li>
                    </ul>

                    <ul style="position:absolute;bottom:8vh; font-weight: bolder;">
                        <li style="color: blue"><a href="{% url 'posts:club_posts' club_name_slug %}">Back To Club Posts</a></li>
                        <li style="color: red;"><a href="{% url 'registration:logout' %}">Logout</a></li>
                    </ul>

                </nav>
            </div>
        </div>

        </div>
    {% endblock %}
<!-- Sidebar -->
{% block mobile_sidebar %}

{% endblock %}

{% block scripts %}
    <script src="{% static 'admin_panel/js/jquery.min.js' %}"></script>
    <script src="{% static 'admin_panel/js/browser.min.js' %}"></script>
    <script src="{% static 'admin_panel/js/breakpoints.min.js' %}"></script>
    <script src="{% static 'admin_panel/js/util.js' %}"></script>
    <script src="{% static 'admin_panel/js/admin_panel.js' %}"></script>
{% endblock %}

{% block custom_scripts %}

{% endblock %}
</body>

</html>

base/templates/base/club/groups.html
{% extends 'base/club/admin_base.html' %}
{% load static %}
{% load widget_tweaks %}


{% block main_content %}
    <section>
        <header class="major">
            <h2>
                Coming Soon
            </h2>


        </header>
    </section>
{% endblock %}

base/templates/base/club/member.html
{% extends 'base/club/admin_base.html' %}
{% load static %}
{% block title %}
    Club Members
{% endblock %}

{% block main_content %}
    <section>
        <header class="major">
            <h2>Pending Requests</h2>
        </header>
        <div class="posts">
            <div class="table-wrapper" style="margin:0 auto;width:100%;">
                <table>
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Email</th>

                    </tr>
                    </thead>
                    <tbody>
                    {% for member in pending_members %}
                        <tr>
                            <td>{{ member.user.get_full_name }}</td>
                            <td>{{ member.user.email }}</td>
                            <td><a href="{% url 'base:approve_member' club_name_slug member.user.username %}"
                                   class="button primary small">Accept</a></td>
                            <td><a href="{% url 'base:remove_member' club_name_slug member.user.username %}"
                                   class="button small">Reject</a></td>
                        </tr>
                    {% endfor %}

                    </tbody>

                </table>
            </div>

        </div>
        <header class="major">
            <div>
                <h2>Members</h2>
            </div>
            <div class="search-box">
                <form action="{% url 'base:add_member_name_as_param' club_name_slug %}" method='get'
                      style="display:flex;justify-content: center;">
                    <input class="search-input" style="margin-right:8px;" type="text" name="username" id="moderatorAdd"
                           placeholder="username">
                    <button type="submit" class="button small" id="new-moderator">Add</button>
                </form>
            </div>
        </header>
        <div class="posts">
            <div class="table-wrapper" style="margin:0 auto;width:100%;">
                <table>
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Year</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for member in members %}
                        <tr>
                            <td>{{ member.user.get_full_name }}</td>
                            <td>{{ member.user.email }}</td>
                            <td>1</td>
                            <td><a href="{% url 'base:remove_member' club_name_slug member.user.username %}"
                                   class="button primary small">Remove</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>

                </table>
            </div>

        </div>

        <header class="major">
            <h2>Followers</h2>
        </header>
        <div class="posts">
            <div class="table-wrapper" style="margin:0 auto;width:100%;">
                <table>
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Year</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for follower in club.following_user_profiles.all %}
                        <tr>
                            <td>{{ folllower.user.get_full_name }}</td>
                            <td>{{ follower.user.email }}</td>
                            <td>1</td>

                        </tr>
                    {% endfor %}
                    </tbody>

                </table>
            </div>

        </div>

    </section>
{% endblock %}

base/templates/base/club/moderator.html
{% extends 'base/club/admin_base.html' %}
{% load static %}

{% block title %}
Club Moderators
{% endblock %}
{% block main_content %}
            <section>
                <header class="major">
                    <div>
                        <h2>Moderators</h2>
                    </div>
                    <div class="search-box">
                        <form action="{% url 'base:add_moderator_name_as_param' club_name_slug %}" method='get' style="display:flex;justify-content: center;">
                            <input class="search-input" style="margin-right:8px;" type="text" name="username" id="moderatorAdd" placeholder="username">
                            <button type="submit" class="button small" id="new-moderator">Add</button>
                        </form>
                    </div>

                </header>
                <div class="posts">
                    <div class="table-wrapper" style="margin:0 auto;width:100%;">
                        <table>
                            <thead>
                            <tr>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Username</th>
                                <th></th>

                            </tr>
                            </thead>
                            <tbody>
                            {% for mod in moderators %}
                                <tr>
                                    <td>{{ mod.user.get_full_name }}</td>
                                    <td>{{ mod.user.email }}</td>
                                    <td>{{ mod.user.username }}</td>
                                    <td><a href="{% url 'base:remove_moderator' club_name_slug mod.user.username %}"
                                           class="button primary small">Remove</a></td>
                                </tr>
                            {% endfor %}
                            </tbody>

                        </table>
                    </div>

                </div>
            </section>
{% endblock %}

base/templates/base/club/pendingPosts.html
{% extends 'base/club/admin_base.html' %}
{% load static %}
{% block title %}
    Club Posts
{% endblock %}

{% block main_content %}
    <section>
        <header class="major">
            <h2>Posts Pending Approval</h2>
        </header>
        <div class="posts">
            <div class="table-wrapper" style="margin:0 auto;width:100%;">
                <table>
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Type</th>
                        <th>Author</th>
                        <th>Public?</th>
                        <th>Notify?</th>

                    </tr>
                    </thead>
                    <tbody>
                    {% for post in pending_posts %}
                        <tr>
                            <td><a href="{% url 'posts:post_detail' club_name_slug post.encrypted_id %}"
                                   class="">{{ post.title|truncatechars_html:30 }}</a></td>
                            <td>
                                {% if post.poll %}
                                Poll
                                {% elif post.event %}
                                Event
                                {% else %}
                                Post
                                {% endif %}
                            </td>
                            <td>{{ post.author.get_full_name }}</td>
                            <td>
                                {% if post.is_public %}
                                Yes
                                {% else %}
                                No
                                {% endif %}
                            </td>
                            <td>
                                {% if post.notify_followers %}
                                Yes
                                {% else %}
                                No
                                {% endif %}
                            </td>
                            <td><a href="{% url 'base:approve_post' club_name_slug post.encrypted_id %}" class="button primary small">Accept</a></td>
                            <td><a href="{% url 'base:reject_post' club_name_slug post.encrypted_id %}" class="button small">Reject</a></td>
                        </tr>
                    {% endfor %}

                    </tbody>

                </table>
            </div>
        </div>
        <header class="major">
            <h2>All posts</h2>
        </header>
        <div class="posts">
            <div class="table-wrapper" style="margin:0 auto;width:100%;">
                <table>
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Type</th>
                        <th>Author</th>

                    </tr>
                    </thead>
                    <tbody>
                    {% for post in club.post_set.all %}
                        {% if post.is_approved %}
                        <tr>
                            <td><a href="{% url 'posts:post_detail' club_name_slug post.encrypted_id %}"
                                   class="">{{ post.title|truncatechars_html:30 }}</a></td>
                            <td>
                                {% if post.poll %}
                                Poll
                                {% elif post.event %}
                                Event
                                {% else %}
                                Post
                                {% endif %}
                            </td>
                            <td>{{ post.author.get_full_name }} ({{ post.author.email }})</td>
                            <td><a href="#" class="button primary small">Remove</a></td>

                        </tr>
                        {% endif %}
                    {% endfor %}

                    </tbody>

                </table>
            </div>
        </div>
    </section>
{% endblock %}