accounts/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.views.generic import TemplateView
from . import calendar_views as calviews
app_name = "accounts"

urlpatterns = [
    path('change-password', views.change_password, name='password-change'),
    path('<slug:club_name>/list-for-president/', views.listForPresident, name='list_for_president'),
    path('<slug:club_name>/list-for-moderator/', views.listForModerator, name='list_for_moderator'),
    path('makeMember/', views.makeMember, name='make_member'),
    path('makeModerator/', views.makeModerator, name='make_moderator'),
    path('profile/', views.profile, name='profile'),

    # Calendar urls
    url(r'^calendar/next/(?P<select>\w+)/(?P<show>\w+)/$', calviews.date, name='date'),
    # path('next/<select>/',views.date,name = "date"),
    # path('back/<select>/',views.date1,name = "date1"),
    url(r'^calendar/back/(?P<select>\w+)/(?P<show>\w+)/$', calviews.date1, name='date1'),
    path('events_enter/<int:date_selected>', calviews.event_enter, name="event_enter"),
    url(r'^calendar/land/(?P<select>\w+)/(?P<show>\w+)/$', calviews.hello, name='index'),
    url(r'^calendar/choose/(?P<select>\w+)/(?P<show>\w+)/$', calviews.choose_event, name='choose'),
]

api/urls.py
from django.urls import path
from rest_framework_simplejwt import views as jwt_views

from api import views

app_name = 'api'

urlpatterns = [
    # Your URLs...
    path('token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('firebasetoken/', views.FirebaseTokenObtainPairView.as_view(), name='firebase_token_obtain_pair'),
    path('token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    path('test', views.HelloView.as_view(), name="hello"),
]

base/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import TemplateView

app_name = "base"

urlpatterns = [

    path('', views.index, name='index'),
    path('clubs/', views.club_home, name='all_clubs'),
    path('clubs/<slug:club_name_slug>/request-join/', views.request_join, name='club_request_join'),
    path('clubs/<slug:club_name_slug>/follow/', views.follow_club, name='club_follow'),
    path('clubs/<slug:club_name_slug>/unfollow/', views.unfollow_club, name='club_unfollow'),

    path('clubs/<slug:club_name_slug>/admin/settings/', views.club_settings, name='club_settings'),
    path('clubs/<slug:club_name_slug>/admin/members/', views.member_list, name='member_list'),
    path('clubs/<slug:club_name_slug>/admin/moderators/', views.moderator_list, name='moderator_list'),
    path('clubs/<slug:club_name_slug>/admin/pending_posts/', views.pending_posts_list, name='pending_posts_list'),
    path('clubs/<slug:club_name_slug>/admin/groups/', views.club_groups, name='club_groups'),

    path('clubs/<slug:club_name_slug>/members/add/', views.add_member, name='add_member_name_as_param'),
    path('clubs/<slug:club_name_slug>/members/add/<str:username>/', views.add_member, name='add_member'),
    path('clubs/<slug:club_name_slug>/members/remove/<str:username>/', views.remove_member, name='remove_member'),
    path('clubs/<slug:club_name_slug>/members/approve/<str:username>/', views.approve_member, name='approve_member'),

    path('clubs/<slug:club_name_slug>/moderators/add/', views.add_moderator, name='add_moderator_name_as_param'),
    path('clubs/<slug:club_name_slug>/moderators/add/<str:username>/', views.add_moderator, name='add_moderator'),
    path('clubs/<slug:club_name_slug>/moderators/remove/', views.remove_moderator,
         name='remove_moderator_name_as_param'),
    path('clubs/<slug:club_name_slug>/moderators/remove/<str:username>/', views.remove_moderator,
         name='remove_moderator'),

    path('clubs/<slug:club_name_slug>/posts/approve/<int:encrypted_id>/', views.approve_post, name="approve_post"),
    path('clubs/<slug:club_name_slug>/posts/reject/<int:encrypted_id>/', views.reject_post, name="reject_post"),

    path('notifications', views.NotificationView.as_view(), name='notifications'),

    path('post_email_temp', views.post_email_temp)

]

club_portal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from base import views as base_views

urlpatterns = [
    path('api/', include("api.urls")),
    path('admin/', admin.site.urls),
    path('registration/', include("registration.urls")),
    path('accounts/', include("accounts.urls")),
    path('posts/', include("posts.urls")),
    # path('', base_views.IndexView.as_view(), name="index"),
    path('', include("base.urls")),
    path('ckeditor/', include("ckeditor_uploader.urls")),
    path('', include('django.contrib.auth.urls')),
    path('random-useless-path/', include("posts.urls")),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from django.contrib.auth.views import TemplateView
from . import views

app_name = "posts"

urlpatterns = [
    path('like_post/<int:id>/', views.likePost, name='like-post'),

    path('events/', views.events, name="events"),
    path('polls/', views.polls, name="polls"),
    path('like_post/<int:id>/', views.likePost, name='like-post'),
    path('edit-post/<int:encrypted_id>/', views.edit_post, name="post-edit"),
    path('edit-poll/<int:encrypted_id>/', views.edit_poll, name="poll-edit"),
    path('edit-event/<int:encrypted_id>', views.events_edit, name="events_edit"),
    # path('add-user-event-interested', views.interested_event)
    path('<slug:club_name_slug>/create-poll/', views.create_poll, name='create_poll'),
    # path('<slug:club_name_slug>/submit-poll/', views.submitPoll, name='submit_poll'),
    path('<slug:club_name_slug>/', views.club_posts, name="club_posts"),
    path('<slug:club_name_slug>/events/', views.club_events, name="club_events"),
    path('<slug:club_name_slug>/polls/', views.club_polls, name="club_polls"),
    path('<slug:club_name_slug>/<int:encrypted_id>', views.post_detail, name="post_detail"),
    path('<slug:club_name_slug>/create', views.create_post, name="post-add"),

    path('<slug:club_name_slug>/<int:encrypted_id>/issue-update', views.post_update, name="post-update"),

    path('<slug:club_name_slug>/<int:encrypted_id>/vote', views.cast_vote, name='cast-vote'),
    path('<slug:club_name_slug>/<int:encrypted_id>/subscribe', views.subscribe, name='subscribe'),
    path('<slug:club_name_slug>/<int:encrypted_id>/unsubscribe', views.unsubscribe, name='unsubscribe'),
    path('<slug:club_name_slug>/<int:encrypted_id>/event_interested', views.event_interested, name='event_interested'),
    path('<slug:club_name_slug>/<int:encrypted_id>/event_not_interested', views.event_uninterested,
         name='event_uninterested'),

    path('<slug:club_name_slug>/events/create', views.events_create, name="events_create"),

    # path('ajax/interested_event', views.interested_event, name="interested_event"),

    path('<slug:club_name_slug>/<int:encrypted_id>/pin', views.pin_post, name="pin-post"),
    path('<slug:club_name_slug>/<int:encrypted_id>/unpin', views.unpin_post, name="unpin-post"),
    path('', views.posts, name='posts'),

]

registration/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views
from registration import views

from . import views

app_name = "registration"


urlpatterns = [


    path('signup/', views.signup,name='signup'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('google-login', views.google_signin, name="google_signin"),

    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('choose-club', views.choose_club, name="choose-club")
]

base/models.py
import os

from django.core.exceptions import ValidationError
from django.db import models, IntegrityError, transaction
from django.contrib.auth.models import User

# Create your models here.
from django.db.models import signals, ProtectedError
from django.dispatch import receiver


def club_name_validator(name):
    if '-' in name:
        raise ValidationError('The name can not contain \'-\'')


def club_logo_upload(instance, filename):
    return os.path.join('clubs', instance.name.replace(' ', '_'), filename)



class Club(models.Model):
    name = models.CharField(max_length=100, validators=[club_name_validator], db_index=True)
    full_name = models.CharField(max_length=100)
    date_formed = models.DateField(auto_now_add=True)
    email = models.EmailField(null=True, blank=True)
    about = models.TextField(help_text="Say a few lines about your club", null=True, blank=True, max_length=500)
    is_active = models.BooleanField(default=True)
    is_supported = models.BooleanField(default=True)
    # num_users = models.IntegerField(default=0)

    back_img = models.ImageField(upload_to=club_logo_upload, blank=True, null=True)

    def __str__(self):
        return self.name

    @property
    def slug(self):
        return self.name.replace(' ', '-')

    def calc_users(self):
        self.num_users = self.clubmember_set.all().count()
        self.save()

    class Meta:
        ordering = ['name']


class ClubSettings(models.Model):
    club = models.OneToOneField(to=Club, on_delete=models.CASCADE)


class ClubMentor(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.PROTECT)
    club = models.ForeignKey(Club, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.club.name + " - " + self.user.username

    class Meta:
        unique_together = ('user', 'club')

    def __str__(self):
        return self.club.name + "-" + self.user.username    


class ClubPresident(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    # We can't allow user to be deleted unless new president is set
    club = models.OneToOneField(Club, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.club.name + "-" + self.user.username

    class Meta:
        unique_together = ('user', 'club')


class ClubModerator(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    club = models.ForeignKey(Club, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.user.username + ' moderator')

    class Meta:
        unique_together = ('user', 'club')

    def __str__(self):
        return self.club.name + "-" + self.user.username
        
class ClubMember(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    club = models.ForeignKey(Club, on_delete=models.CASCADE)
    is_approved = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username + '-' + self.club.name

    class Meta:
        unique_together = ('user', 'club')


class Notification(models.Model):
    sender = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="sentNotifications")
    club = models.ForeignKey(Club, on_delete=models.CASCADE, null=True, blank=True)
    # is_read = models.BooleanField(default=False, null=False)
    receivers = models.ManyToManyField(
        User, related_name="receivedNotifications", blank=True)

    title = models.TextField()
    message = models.TextField()

    sent_at = models.DateTimeField(auto_now_add=True)


class EmailProvider(models.Model):
    name = models.TextField()

    current = models.IntegerField(default=0)
    limit = models.IntegerField(null=False)

    # in days, when to reset the current count
    reset = models.IntegerField()

    last_reset = models.DateTimeField(auto_now_add=True)


# @receiver(signals.post_save, sender=Club)
# def random_back_image(sender, instance, created, **kwargs):
#     if created:
#
#         if not hasattr(instance.back_img,'url'):
#             pass

@receiver(signals.post_save, sender=ClubMember)
def member_follow_club(sender, instance, created, **kwargs):
    # If a user is made a moderator, also make him a member of the club
    try:
        instance.user.userprofile.following_clubs.add(instance.club)
    except IntegrityError:
        # User is already a member. Do Nothing
        pass


@receiver(signals.post_save, sender=ClubModerator)
def moderator_add_member(sender, instance, created, **kwargs):
    # If a user is made a moderator, also make him a member of the club
    try:
        with transaction.atomic():  # We need to make atomic as code may throw integrity error
            ClubMember.objects.create(user=instance.user, club=instance.club, is_approved=True)
    except IntegrityError:
        # User is already a member. Do Nothing
        pass


@receiver(signals.post_save, sender=ClubPresident)
def president_add_moderator_member(sender, instance, created, **kwargs):
    # If a user is made a president, also make him a member and moderator of the club
    try:
        with transaction.atomic():  # We need to make atomic as code may throw integrity error
            ClubModerator.objects.create(user=instance.user, club=instance.club)
        # Just making moderator is enough, as while making moderator, the above signal will be called, which will make him a member
    except IntegrityError:
        # User is already a moderator. Do Nothing
        pass


@receiver(signals.post_save, sender=ClubMentor)
def mentor_add_moderator(sender, instance, created, **kwargs):
    try:
        with transaction.atomic():
            ClubModerator.objects.create(user=instance.user, club=instance.club)
    except IntegrityError:
        # User is already a moderator. Do Nothing
        pass


@receiver(signals.pre_delete, sender=ClubModerator)
def moderator_delete_protect_president(sender, instance, **kwargs):
    # If a moderator is deleted, and if user is also president, prevent delete of moderator
    if instance.club.clubpresident.user == instance.user:
        raise ProtectedError("Can not delete moderator who is also president", instance)


@receiver(signals.pre_delete, sender=ClubMember)
def member_delete_moderator(sender, instance, **kwargs):
    # If a member is deleted, also delete moderator

    mod_instance = ClubModerator.objects.filter(user=instance.user, club=instance.club)
    if mod_instance.exists():
        mod_instance.delete()

base/forms.py
from django import forms
from .models import Club


class ClubForm(forms.ModelForm):
    class Meta:
        model = Club
        fields = ['name', 'full_name', 'email', 'about', 'back_img']

base/templates/base/base.html
{% load static %}
{% load blog_tags %}
{% load club_user_filters %}
<!doctype html>
<html>
<head>

    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    {% block head %}
    {% endblock %}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
          integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    {#    <link rel="stylesheet" href="{% static 'posts/css/fontawesome.min.css' %}">#}
    <link rel="stylesheet" href="{% static "css/navbar-footer.css" %}">
</head>
<body class="is-preload">
{% block nav %}
    <section id="header" >

        <nav class="navbar navbar-static-top navbar-expand-lg navbar-light bg-light w-100 pr-5 p-0 flex align-items-center"
             style="top:0;position: fixed;">
            <a class="navbar-brand" href="{% url 'base:index' %}" style="font-weight: bolder; font-size: 220%;padding-left: 5vh;">IIITS Clubs</a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
                    style="height:2.8125rem!important;">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto px-3">


                    <li class="nav-item px-3 nav-item-scroll">
                        <a class="nav-link" href="{% url 'posts:posts' %}">All Posts</a>
                    </li>
                    <li class="nav-item px-3">
                        <a class="nav-link" href="{% url 'base:all_clubs' %}">Clubs</a>
                    </li>

                    <li class="nav-item dropdown px-3 nav-item-scroll">

                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Club Posts
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            {% for club in clubs %}
                                <a class="dropdown-item"
                                   href="{% url 'posts:club_posts' club.name|clubslug %}">{{ club.name|title }}</a>
                            {% endfor %}
                            {#                        <a class="dropdown-item" href="#">IOTA</a>#}
                            {#                        <a class="dropdown-item" href="#">Gradient</a>#}
                            {#                        <a class="dropdown-item" href="#">Photography Club</a>#}
                        </div>
                    </li>

                    {% if club_slug %}

                        {% if request.user|is_user_moderator:club %}
                            <li class="nav-item px-3">
                                <a class="nav-link" href="{% url 'base:club_settings' club.name|clubslug %}">Club-Admin</a>
                            </li>
                        {% endif %}
                    {% endif %}
                    {% if request.user.is_authenticated %}

                        <li class="nav-item px-3 nav-item-scroll">
                            {#                    <a class="nav-link" href="#">Login</a>#}
                            {#                     <img src="{% static "images/download.jpg" %}" alt="image" height="50" width="50" style="border-radius:25px;">#}
                            {#                     <span>Vineet</span>#}
                            <a class="nav-link dropdown-toggle" href="#" id="profileDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <div class="chip">
                                    {% if request.user.userprofile.profile_pic %}
                                        <img src="{{ request.user.userprofile.profile_pic.url }}" alt="Person"
                                             width="96"
                                             height="96"/>
                                    {% elif request.user.googleauth.profile_pic_link %}
                                        <img src="{{ request.user.googleauth.profile_pic_link }}" alt="Person"
                                             width="96"
                                             height="96"/>
                                    {% else %}
                                        <img src="{% static "posts/images/pic10.jpg" %}" alt="Person" width="96"
                                             height="96"/>

                                    {% endif %}
                                    {#                                <img src="{% static "images/download.jpg" %}" alt="Person" width="96" height="96">#}
                                    {{ request.user.get_full_name }}
                                </div>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="profileDropdown" style="margin-right:6%!important;">
                                <a class="dropdown-item" href="{% url 'accounts:profile' %}">Profile</a>
                                {% if request.user|is_user_clc_mod %}
                                    <a class="dropdown-item" href="{% url 'posts:club_posts' 'Campus-Life-Committee' %}">CLC Portal</a>
                                {% endif %}
                                <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                                <a class="dropdown-item" href="{% url 'accounts:index' select='1' show='1'%}">Calendar <sup style="color: red">Beta</sup></a>

                            </div>


                            {#                    <div class="dropdown">#}
                            {#                        <button class="dropbtn">#}
                            {#                            <a class="nav-link dropdown-toggle" href="#" id="profileDropdown" role="button"#}
                            {#                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">#}
                            {#                                <div class="chip">#}
                            {#                                    <img src="{% static "images/download.jpg" %}" alt="Person" width="96" height="96">#}
                            {#                                    John Doe#}
                            {#                                </div>#}
                            {#                            </a>#}
                            {#                        </button>#}
                            {#                        <div class="dropdown-content">#}
                            {#                            <a href="#">Link 1</a>#}
                            {#                            <a href="#">Link 2</a>#}
                            {#                            <a href="#">Link 3</a>#}
                            {#                        </div>#}
                            {#                    </div>#}
                        </li>
                    {% else %}
                        {% comment %}<li class="nav-item px-3 nav-item-scroll">
                            <a class="nav-link"
                               href="{% url 'registration:login' %}?next={{ request.path }}">Signup</a>
                        </li>{% endcomment %}
                        <li class="nav-item px-3 nav-item-scroll">

                            <a class="nav-link" href="{% url 'registration:login' %}?next={{ request.path }}">Login/Signup</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </section>

{% endblock nav %}
<!-- Wrapper -->
<div id="wrapper">

    <!-- Header -->
    <!-- Header -->
    {#    <header id="header">#}
    {##}
    {#        <a href="#" class="logo">#}
    {#            <img src="{% static 'posts/images/logo-iota.jpg' %}" alt="" class="logo-club"/>#}
    {#        </a>#}
    {#        <nav class="main">#}
    {#            <ul>#}
    {#                <li class="search">#}
    {#                    <a class="fa-search" href="#search">Search</a>#}
    {#                    <form id="search" method="get" action="#">#}
    {#                        <input type="text" name="query" placeholder="Search"/>#}
    {#                    </form>#}
    {#                </li>#}
    {#                <li class="menu">#}
    {#                    <a class="fa-bars" href="#menu">Menu</a>#}
    {#                </li>#}
    {#            </ul>#}
    {#        </nav>#}
    {#    </header>#}




    {% block content %}
    {% endblock %}

</div>

<div id="wrapper" class="p-0">
    <!-- Footer -->
    <footer id="footer" class="w-100 text-center">
        <div class="inner">
            <ul class=".d-none .d-lg-block">
                <li class="px-3"><i class="fab fa-twitter"></i></li>
                <li class="px-3"><i class="fab fa-facebook-f"></i></li>
                <li class="px-3"><i class="fab fa-instagram"></i></li>
                <li class="px-3"><i class="fab fa-github"></i></li>
                <li class="px-3"><i class="fab fa-linkedin-in"></i></li>
            </ul>
            <ul class="copyright">
                <li class="text-dark">&copy; Copyright 2019</li>
                <li class="text-dark">Made By <span class="author-name">IOTA</span></li>
            </ul>
        </div>
    </footer>
</div>

<!-- Scripts -->

<script src="{% static 'posts/js/jquery.min.js' %}"></script>
{#<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"#}
{#        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"#}
{#        crossorigin="anonymous"></script>#}
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>


<script src="{% static 'posts/js/browser.min.js' %}"></script>
<script src="{% static 'posts/js/breakpoints.min.js' %}"></script>
<script src="{% static 'posts/js/util.js' %}"></script>
<script src="{% static 'posts/js/main.js' %}"></script>


{% block script %}

{% endblock %}

</body>
</html>

base/templates/base/layout.html
{% extends 'base/base.html' %}
{% load static %}

{% block head %}
{% endblock %}


{% block content %}
{% endblock %}

{% block script %}
{% endblock %}

base/templates/base/moderator.html
{% load static %}
<!DOCTYPE HTML>
<html>
<head>
    <title>Editorial by HTML5 UP</title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no"/>
    <link rel="stylesheet" href="{% static 'admin_panel/css/admin_panel.css' %}"/>
</head>
<body class="is-preload">
<!-- Wrapper -->
<div id="wrapper">
    <!-- Main -->
    <div id="main">
        <div class="inner">
            <!-- Section -->
            <section>
                <header class="major">
                    <div>
                        <h2>Moderators</h2>
                    </div>
                    <div class="search-box">
                        <input class="search-input" type="text" name="addMember" id="moderatorAdd">
                        <a href="#" class="button small">Add</a>
                    </div>

                </header>
                <div class="posts">
                    <div class="table-wrapper" style="margin:0 auto;width:100%;">
                        <table>
                            <thead>
                            <tr>
                                <th>Name</th>
                                <th>Description</th>

                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>Lorem Ipsum</td>
                                <td>Ante turpis integer aliquet porttitor.</td>
                            </tr>
                            <tr>
                                <td>Lorem Ipsum</td>
                                <td>Vis ac commodo adipiscing arcu aliquet.</td>
                            </tr>
                            <tr>
                                <td>Lorem Ipsum</td>
                                <td> Morbi faucibus arcu accumsan lorem.</td>
                            </tr>
                            <tr>
                                <td>Lorem Ipsum</td>
                                <td>Vitae integer tempus condimentum.</td>
                            </tr>
                            <tr>
                                <td>Lorem Ipsum</td>
                                <td>Ante turpis integer aliquet porttitor.</td>
                            </tr>
                            </tbody>

                        </table>
                    </div>

                </div>
            </section>

        </div>
    </div>

    <!-- Sidebar -->
    <div id="sidebar">
        <div class="inner">
            <nav id="menu">
                <header class="major">
                    <h2>IOTA</h2>
                </header>
                <ul>
                    <li><a href="{% url 'base:member_list' %}">Members</a></li>
                    <li><a href="{% url 'base:moderator_list' %}">Moderators</a></li>
                    <li><a href="{% url 'base:pending_posts_list' %}">Posts</a></li>
                </ul>
            </nav>
        </div>
    </div>

</div>

<!-- Scripts -->
<script src="{% static 'admin_panel/js/jquery.min.js' %}"></script>
<script src="{% static 'admin_panel/js/browser.min.js' %}"></script>
<script src="{% static 'admin_panel/js/breakpoints.min.js' %}"></script>
<script src="{% static 'admin_panel/js/util.js' %}"></script>
<script src="{% static 'admin_panel/js/admin_panel.js' %}"></script>


</body>
</html>

base/templates/base/notifications.html
{% extends "base/base.html" %}

{% block content %}
    <section style="margin-top: 15vh">
    <div class="w-75" >
    {% for notification in user.receivedNotifications.all %}
       
    <div class="row accordion">
        <div class="col-2">
            <img class="img-fluid" src="https://image.shutterstock.com/image-vector/profile-placeholder-male-default-gray-450w-535853263.jpg"/>    
        </div> 
        <div class="col-10">   
            <h5 class="font-weight-bold">
                {{notification.sender.username}} sent you a message
            </h5>
            <div class="accordion-item" style="width:100%;">
                <a> {{notification.title}} </a>
                <div class="content">
                    {{notification.message}}
                </div>
            </div>
        </div>
    </div>
        <br/><br/>
    {% endfor %}
    </div>
    </section>
{% endblock content %}

{% block script %}
    <script>
        const items = document.querySelectorAll(".accordion a");
        function toggleAccordion(){
            this.classList.toggle('active');
            this.nextElementSibling.classList.toggle('active');
        }
        items.forEach(item => item.addEventListener('click', toggleAccordion));
    </script>
{% endblock script %}