api/urls.py
from django.urls import path
from rest_framework_simplejwt import views as jwt_views

from api import views

app_name = 'api'

urlpatterns = [
    # Your URLs...
    path('token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('firebasetoken/', views.FirebaseTokenObtainPairView.as_view(), name='firebase_token_obtain_pair'),
    path('token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    path('test', views.HelloView.as_view(), name="hello"),
]

base/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import TemplateView

app_name = "base"

urlpatterns = [

    path('', views.index, name='index'),
    path('clubs/', views.club_home, name='all_clubs'),
    path('clubs/<slug:club_name_slug>/request-join/', views.request_join, name='club_request_join'),
    path('clubs/<slug:club_name_slug>/follow/', views.follow_club, name='club_follow'),
    path('clubs/<slug:club_name_slug>/unfollow/', views.unfollow_club, name='club_unfollow'),

    path('clubs/<slug:club_name_slug>/admin/settings/', views.club_settings, name='club_settings'),
    path('clubs/<slug:club_name_slug>/admin/members/', views.member_list, name='member_list'),
    path('clubs/<slug:club_name_slug>/admin/moderators/', views.moderator_list, name='moderator_list'),
    path('clubs/<slug:club_name_slug>/admin/pending_posts/', views.pending_posts_list, name='pending_posts_list'),
    path('clubs/<slug:club_name_slug>/admin/groups/', views.club_groups, name='club_groups'),

    path('clubs/<slug:club_name_slug>/members/add/', views.add_member, name='add_member_name_as_param'),
    path('clubs/<slug:club_name_slug>/members/add/<str:username>/', views.add_member, name='add_member'),
    path('clubs/<slug:club_name_slug>/members/remove/<str:username>/', views.remove_member, name='remove_member'),
    path('clubs/<slug:club_name_slug>/members/approve/<str:username>/', views.approve_member, name='approve_member'),

    path('clubs/<slug:club_name_slug>/moderators/add/', views.add_moderator, name='add_moderator_name_as_param'),
    path('clubs/<slug:club_name_slug>/moderators/add/<str:username>/', views.add_moderator, name='add_moderator'),
    path('clubs/<slug:club_name_slug>/moderators/remove/', views.remove_moderator,
         name='remove_moderator_name_as_param'),
    path('clubs/<slug:club_name_slug>/moderators/remove/<str:username>/', views.remove_moderator,
         name='remove_moderator'),

    path('clubs/<slug:club_name_slug>/posts/approve/<int:encrypted_id>/', views.approve_post, name="approve_post"),
    path('clubs/<slug:club_name_slug>/posts/reject/<int:encrypted_id>/', views.reject_post, name="reject_post"),

    path('notifications', views.NotificationView.as_view(), name='notifications'),

    path('post_email_temp', views.post_email_temp)

]

club_portal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from base import views as base_views

urlpatterns = [
    path('api/', include("api.urls")),
    path('admin/', admin.site.urls),
    path('registration/', include("registration.urls")),
    path('accounts/', include("accounts.urls")),
    path('posts/', include("posts.urls")),
    # path('', base_views.IndexView.as_view(), name="index"),
    path('', include("base.urls")),
    path('ckeditor/', include("ckeditor_uploader.urls")),
    path('', include('django.contrib.auth.urls')),
    path('random-useless-path/', include("posts.urls")),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from django.contrib.auth.views import TemplateView
from . import views

app_name = "posts"

urlpatterns = [
    path('like_post/<int:id>/', views.likePost, name='like-post'),

    path('events/', views.events, name="events"),
    path('polls/', views.polls, name="polls"),
    path('like_post/<int:id>/', views.likePost, name='like-post'),
    path('edit-post/<int:encrypted_id>/', views.edit_post, name="post-edit"),
    path('edit-poll/<int:encrypted_id>/', views.edit_poll, name="poll-edit"),
    path('edit-event/<int:encrypted_id>', views.events_edit, name="events_edit"),
    # path('add-user-event-interested', views.interested_event)
    path('<slug:club_name_slug>/create-poll/', views.create_poll, name='create_poll'),
    # path('<slug:club_name_slug>/submit-poll/', views.submitPoll, name='submit_poll'),
    path('<slug:club_name_slug>/', views.club_posts, name="club_posts"),
    path('<slug:club_name_slug>/events/', views.club_events, name="club_events"),
    path('<slug:club_name_slug>/polls/', views.club_polls, name="club_polls"),
    path('<slug:club_name_slug>/<int:encrypted_id>', views.post_detail, name="post_detail"),
    path('<slug:club_name_slug>/create', views.create_post, name="post-add"),

    path('<slug:club_name_slug>/<int:encrypted_id>/issue-update', views.post_update, name="post-update"),

    path('<slug:club_name_slug>/<int:encrypted_id>/vote', views.cast_vote, name='cast-vote'),
    path('<slug:club_name_slug>/<int:encrypted_id>/subscribe', views.subscribe, name='subscribe'),
    path('<slug:club_name_slug>/<int:encrypted_id>/unsubscribe', views.unsubscribe, name='unsubscribe'),
    path('<slug:club_name_slug>/<int:encrypted_id>/event_interested', views.event_interested, name='event_interested'),
    path('<slug:club_name_slug>/<int:encrypted_id>/event_not_interested', views.event_uninterested,
         name='event_uninterested'),

    path('<slug:club_name_slug>/events/create', views.events_create, name="events_create"),

    # path('ajax/interested_event', views.interested_event, name="interested_event"),

    path('<slug:club_name_slug>/<int:encrypted_id>/pin', views.pin_post, name="pin-post"),
    path('<slug:club_name_slug>/<int:encrypted_id>/unpin', views.unpin_post, name="unpin-post"),
    path('', views.posts, name='posts'),

]

posts/models.py
import os

from django.core.exceptions import ValidationError
from django.db import models
from django.contrib.auth.models import User
from django.db.models import signals
from django.dispatch import receiver
from django.utils import timezone

from base.models import Club
from ckeditor_uploader.fields import RichTextUploadingField
# Create your models here.
from posts.utils import encrypt_id


def cover_image_upload_path(instance, filename):
    return os.path.join('clubs', instance.club.name, 'posts', str(instance.id), 'cover', filename)


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    club = models.ForeignKey(Club, on_delete=models.CASCADE)

    title = models.CharField(max_length=150)
    body = RichTextUploadingField(blank=True)  # from ckeditor
    is_public = models.BooleanField(default=False,
                                    help_text="If unchecked, only the members of the club can see this post.")
    cover_image = models.ImageField(null=True, blank=True,
                                    help_text="Images larger than 2.2 MBs are not supported. \n You may get a 403 error if you try to upload images that exceed this size")

    created = models.DateTimeField(auto_now_add=True)

    last_updated = models.DateTimeField(auto_now=True)

    votes = models.IntegerField(default=0)

    encrypted_id = models.BigIntegerField(default=0, editable=False, db_index=True)

    subscribed_users = models.ManyToManyField(User, blank=True, related_name="subscribers")

    is_approved = models.BooleanField(default=False)
    is_published = models.BooleanField(default=True,
                                       help_text="Uncheck this if you just want to save as draft and edit later before publishing")

    notify_followers = models.BooleanField(default=False,
                                           help_text="Check this if you would like to send email to all members/followers about this new post")

    liked_users = models.ManyToManyField(User, related_name='liked_users', blank=True)

    no_likes = models.IntegerField(default=0)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.title[:20]

    def reclac_likes(self):
        self.no_likes = self.liked_users.count()
        self.save()


class PostApprover(models.Model):
    post = models.OneToOneField(to=Post, on_delete=models.CASCADE)
    user = models.ForeignKey(to=User, on_delete=models.PROTECT)
    approved_on = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ['post', 'user']


class PostUpdate(models.Model):
    author = models.ForeignKey(to=User, on_delete=models.CASCADE)
    post = models.ForeignKey(to=Post, on_delete=models.CASCADE)
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['post', '-last_updated']


class PinnedPost(models.Model):
    post = models.OneToOneField(to=Post, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-post__last_updated']

    def clean(self):
        if self.post.is_approved is False:
            raise ValidationError("A post that has not been approved can not be pinned")


class Image(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    image = models.ImageField()


class Poll(models.Model):
    post = models.OneToOneField(Post, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True, help_text="Make it False when you wish to stop collecting votes")

    track_votes = models.BooleanField(default=True, help_text="If checked, it will be tracked, which user has voted for\
                                        which option. If unchecked, voting will be anonymous. (In both cases, each user \
                                        can vote only once)"
                                      )

    @property
    def total_votes(self):
        count = 0
        for option in self.option_set.all():
            count += option.num_votes

        return count


class Option(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    option_text = models.CharField(max_length=150)
    num_votes = models.IntegerField(default=0)

    def __str__(self):
        return self.poll.post.title[:10] + "... : " + self.option_text + ":" + str(self.num_votes)


class Vote(models.Model):
    poll = models.ForeignKey(to=Poll, on_delete=models.CASCADE)
    option = models.ForeignKey(Option, null=True, blank=True, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    time_stamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ['user', 'poll']  # One user can thus vote for only 1 option

    def __str__(self):
        return self.user.username + "-" + self.poll.post.title[:10] + "..."


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=264)
    time_stamp = models.DateTimeField(auto_now_add=True)


class Event(models.Model):
    post = models.OneToOneField(Post, on_delete=models.CASCADE)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    venue = models.CharField(max_length=200)
    interested_users = models.ManyToManyField(User, blank=True)


class News(models.Model):
    message = models.CharField(max_length=200)
    post = models.OneToOneField(Post, on_delete=models.CASCADE)

    class Meta:
        ordering = ['post']


@receiver(signals.post_save, sender=Post)
def create_profile_and_oauth(sender, instance, created, **kwargs):
    if created:
        instance.encrypted_id = encrypt_id(instance.id)
        instance.save()

posts/forms.py
from django import forms
from .models import Post, PostUpdate, Event, Poll


class PostFilterForm(forms.Form):
    page = forms.IntegerField(required=False)
    events_only = forms.BooleanField(required=False, initial=False)
    polls_only = forms.BooleanField(required=False, initial=False)
    query = forms.CharField(required=False)

    def filter_posts(self, posts):
        if self.is_valid():
            if self.cleaned_data['events_only']:
                if self.cleaned_data['polls_only']:
                    posts = posts.exclude(event=None, poll=None)
                posts = posts.exclude(event=None)

            if self.cleaned_data['polls_only']:
                posts = posts.exclude(poll=None)

            if self.cleaned_data['query'] != 'None':
                posts = posts.filter(title__contains=self.cleaned_data['query'])

        return posts

print('abc')
    
class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ('start_date', 'end_date', 'venue')


class PostCreationForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("title", "body", "cover_image", 'is_public', 'is_published', 'notify_followers')


class PostUpdateForm(forms.ModelForm):
    class Meta:
        model = PostUpdate
        fields = ['content']


class PollCreateForm(forms.ModelForm):
    class Meta:
        model = Poll
        fields = ['track_votes']


class PollUpdateForm(forms.ModelForm):
    class Meta:
        model = Poll
        fields = ['track_votes']

posts/templates/posts/event_create.html
{% extends 'base/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block head %}
    <link rel="stylesheet" href="{% static 'posts/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'posts/css/post_edit.css' %}">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    <link rel="stylesheet" href="{% static 'posts/css/jquery.timepicker.min.css' %}">

{% endblock %}

{% block content %}

    <div class="container mt-4" style="margin-top: 100px">


        {% for field, errors in postform.errors.items %}
            {% for error in errors %}
                {{ field }} - {{ error }}
            {% endfor %}
        {% endfor %}

        {% for field, errors in eventform.errors.items %}
            {% for error in errors %}
                {{ field }} - {{ error }}
            {% endfor %}
        {% endfor %}



        <h2 style="margin-bottom: 0;">Create Event</h2>
        <form method="POST" id="event_submit" enctype="multipart/form-data" action="">
            {% csrf_token %}
            {{ postform.media }}

            <p>
                <span style="font-weight: 600;">Title:</span>
                {{ postform.title }}
                {{ postform.title.help_text }}
            </p>


            <div class="mt-6">
                <span style="font-weight: 600; vertical-align: top;margin-right:10px;">Body:</span>
                {{ postform.body }}
            </div>

            <div class="checkbox" style="margin-top:10px;">
                    <label for="id_cover_image">Cover image:</label>
                    <input type="file" name="cover_image" accept="image/*" id="id_cover_image">
                    <p>{{ postform.cover_image.help_text|linebreaksbr }}</p>
                </div>


            {#            <div class="">#}
            <div class="checkbox">

                <span>{{ postform.is_public.label_tag }}</span>
                <span style="float:left;">{{ postform.is_public }}</span>
                <span class="helpText">{{ postform.is_public.help_text }}</span>
            </div>
            <div class="checkbox">
                {{ postform.is_published.label_tag }}
                <span class="mt-2">{{ postform.is_published }}</span>
                <span class="helpText">{{ postform.is_published.help_text }}</span>
            </div>
            {#            </div>#}

            <div class="checkbox">
                {{ postform.notify_followers.label_tag }}
                <span class="mt-2">{{ postform.notify_followers }}</span>
                <span class="helpText">{{ postform.notify_followers.help_text }}</span>
            </div>

            <div class="row mb-4 mt-4">
                <div class="col-lg-6">
                    <strong>Start Date:</strong>
                    <input type="text" name="start_date" class="datepicker" size="10" required id="id_start_date"
                           autocomplete="off">
                </div>
                <div class="col-lg-6">
                    <strong>End Date:</strong>
                    <input type="text" name="end_date" class="datepicker" size="10" required id="id_end_date"
                           autocomplete="off">
                </div>
            </div>


            <div class="row mb-4 mt-4">
                <div class="col-lg-6">
                    <label for="id_start_time_1">Start Time</label>
                    <input type="text" id="id_start_time" name="start_time" class="timepicker">
                </div>
                <div class="col-lg-6">
                    <label for="id_end_time_1">End Time</label>
                    <input type="text" id="id_end_time" name="end_time" class="timepicker">
                </div>
            </div>

            <div>
                <strong>Venue:</strong>
                {{ eventform.venue }}
            </div>


            <input type='submit' id="submit_button" style="margin-top: 10px;">
        </form>
    </div>



{% endblock %}

{% block script %}

    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="{% static 'posts/js/jquery.timepicker.js' %}"></script>
    <script>
        $(function () {
            $(".datepicker").datepicker();
            $('.timepicker').timepicker({'timeFormat': 'H:i:s'});


            document.querySelector('#event_submit').addEventListener('submit', (e) => {

                const startTime = document.querySelector('#id_start_time').value;
                const endTime = document.querySelector('#id_end_time').value;

                const startDay = document.querySelector('#id_start_date');
                const endDay = document.querySelector('#id_end_date');


                startDay.value = `${startDay.value} ${startTime}`;
                endDay.value = `${endDay.value} ${endTime}`;


                console.log(document.querySelector('#id_start_date').value);
                console.log(document.querySelector('#id_end_date').value);
            });

        });
    </script>




{% endblock %}

posts/templates/posts/general_post.html
{% extends 'base/base.html' %}
{% load blog_tags %}
{% load static %}


{% block head %}
    <title>Posts</title>
    <link rel="stylesheet" href="{% static 'posts/css/main.css' %}">
    <link rel="stylesheet" href="{% static "posts/css/loader.css" %}"/>
{% endblock %}


{% block content %}


    <div id="main" style="margin-top: 5vh;">
        <div class="infinite-container" id="all_posts">
            {% for post in posts %}
                <div class="infinite-item">
                    <article class="post">
                        <header>
                            <div class="title">
                                <h2>
                                    <a href="{% url 'posts:post_detail'  post.club.name|clubslug post.encrypted_id %}">{{ post.title }}</a>
                                </h2>
{#                                <p>Lorem ipsum dolor amet nullam consequat etiam feugiat</p>#}
                            </div>
                            <div class="meta">
                                <time class="published" datetime="2015-10-22">{{ post.created }}</time>
                                <a href="#" class="author"><span class="name">{{ post.author.get_full_name }}</span>
                                    <img src="{% static "posts/images/pic10.jpg" %}" alt=""/></a>
                                {#                                TODO Put author name and profile pic here#}
                            </div>
                        </header>
                        {% if post.cover_image %}
                            <a href="{% url 'posts:post_detail' post.club.name|clubslug post.encrypted_id %}" class="image featured">
                                <img src="{{ post.cover_image.url }}" alt="Cover Image"/>
                            </a>
                        {% endif %}
                        <p>
                            {{ post.body|truncatechars_html:450|removeImg|safe}}
                        </p>
                        <footer>
                            <ul class="actions">
                                <li><a href="{% url 'posts:post_detail' post.club.name|clubslug post.encrypted_id %}"
                                       class="button large">Continue Reading</a>
                                </li>
                            </ul>
                            {% comment %}<ul class="stats">
                                <i class="fas fa-heart"></i>
                                <li><a href="#" class="icon fa-heart fa-2x">{{ post.votes }}</a></li>
                                <li><a href="#" class="icon fa-comment fa-2x">128</a></li>
                            </ul>{% endcomment %}
                        </footer>
                    </article>
                </div>
            {% empty %}
                <div style="text-align: center;">
                <h2>No Recent Posts Available!</h2>
                <div>You might not be seeing any posts because you are not following any clubs. Head over to the
                    <a style="color: #2ebaae !important;" href="{% url 'base:all_clubs' %}"> clubs page </a> to follow some.</div>
                </div>

            {% endfor %}
        </div>
        {% if posts.has_next %}
            <a style="display:none;" class="infinite-more-link"
               href="?page={{ posts.next_page_number }}&{% for field in filter_form %}{% if field.name != 'page' %}{{ field.name }}={{ field.value }}&{% endif %}{% endfor %}">More</a>
        {% endif %}

        <div style="width: 100%; text-align: center; display: none" class="loading">
            <div class="lds-ripple">
                <div></div>
                <div></div>
                <div></div>
            </div>
        </div>

        <!-- Pagination -->
        {#        <ul class="actions pagination">#}
        {#            <li><a href="" class="disabled button large previous">Previous Page</a></li>#}
        {#            <li><a href="#" class="button large next">Next Page</a></li>#}
        {#        </ul>#}

    </div>
    <section id="sidebar" style="margin-top: 5vh;">
	{% comment %}
        <!-- About -->
        <section class="blurb">
            <h2>About</h2>
            <p>
                {{ club.about|safe|truncatechars_html:150 }}
            </p>
{#            <ul class="actions">#}
{#                <li><a href="#" class="button">Learn More</a></li>#}
{#            </ul>#}
        </section>

	{% endcomment %}

        <section style="">
            <h2 style="color: crimson">Note</h2>
            <p style="color: crimson">
                This section displays only the public posts of clubs you ARE FOLLOWING. To see private posts of clubs of which you are a member, you should go to the individual club page.

            </p>
        </section>
        <!-- Mini Posts -->
        <section>
            <div class="mini-posts">
                <h3>Pinned Posts</h3>

                {% for p_post in pinned_posts %}
                    <!-- Mini Post -->
                    <article class="mini-post">
                        <header>
                            <h3><a href="{% url 'posts:post_detail' p_post.post.club.name|clubslug p_post.post.encrypted_id %}">{{ p_post.post.title|truncatechars_html:26 }}</a></h3>
                            <time class="published" datetime="2015-10-18">{{ p_post.post.created }}</time>

                            <a href="{% url 'posts:post_detail' p_post.post.club.name|clubslug p_post.post.encrypted_id %}" class="author">
                                <img src="{% static "posts/images/pic10.jpg" %}" alt=""/></a>
{#                            <p>{{ p_post.post.body|safe|truncatechars_html:28 }}</p>#}

                        </header>
                        {% if p_post.post.cover_image %}
                            <a href="{% url 'posts:post_detail' p_post.post.club.name|clubslug p_post.post.encrypted_id %}" class="image">
                                <img src="{{ p_post.post.cover_image.url }}" alt=""/></a>
                        {% endif %}

                    </article>

                {% empty %}
                    <p>No Pinned Posts</p>
                {% endfor %}

            </div>
        </section>

        <!-- Posts List -->
        <section>
            <h3>Top Posts</h3>
            <ul class="posts">
                {% for post in top_posts %}
                <li>
                    <article>
                        <header>
                            <h3><a href="{% url 'posts:post_detail' post.club.name|clubslug post.encrypted_id %}">{{ post.title }}</a></h3>
                            <time class="published" datetime="2015-10-10">{{ post.created }}</time>
                        </header>
                        <a href="#" class="author">
                            <img src="{% static "posts/images/pic10.jpg" %}" alt=""/></a>
{#                        TODO Put user profile pic here#}
                    </article>
                </li>

                {% endfor %}
            </ul>
        </section>







    </section>


{% endblock %}


{% block script %}
    <script src="{% static 'common_assests/imakewebthings-waypoints-34d9f6d/lib/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'common_assests/imakewebthings-waypoints-34d9f6d/lib/shortcuts/infinite.min.js' %}"></script>
    <script>
        var infinite = new Waypoint.Infinite({
            element: $('.infinite-container')[0],
            onBeforePageLoad: function () {
                $('.loading').show();
            },
            onAfterPageLoad: function ($items) {
                $('.loading').hide();
                {#$('.collapsible').collapsible();#}
            }
        });
    </script>

{% endblock %}

posts/templates/posts/poll_create.html
{% extends 'base/base.html' %}
{% load static %}

{% block head %}

    <link rel="stylesheet" href="{% static 'css/poll_create.css' %}">
    <link rel="stylesheet" href="{% static 'posts/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'posts/css/post_edit.css' %}">

{% endblock %}

{% block content %}

    <div class="container" style="margin-top: 5vh;">
        <h2 style="margin-bottom: 0;">Create Poll</h2>
        Add some details then select options


        <div class="options">
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ post_create_form.media }}

                <p>
                    <span style="font-weight: 600;">Title:</span>
                    {{ post_create_form.title }}
                    {{ post_create_form.title.help_text }}
                </p>

                <span style="font-weight: 600; vertical-align: top;margin-right:10px;">Body:</span>
                {{ post_create_form.media }}
                {{ post_create_form.body }}

                <div class="checkbox" style="margin-top:10px;">
                    <label for="id_cover_image">Cover image:</label>
                    <input type="file" name="cover_image" accept="image/*" id="id_cover_image">
                    <p>{{ post_create_form.cover_image.help_text|linebreaksbr }}</p>
                </div>

                <div class="checkbox">

                    {{ post_create_form.is_public.label_tag }}
                    {{ post_create_form.is_public }}
                    <span class="helpText">{{ post_create_form.is_public.help_text }}</span>

                </div>

                <div class="checkbox">
                    {{ post_create_form.is_published.label_tag }}
                    {{ post_create_form.is_published }}
                    <span class="helpText">{{ post_create_form.is_published.help_text }}</span>
                </div>

                <div class="checkbox">
                    {{ post_create_form.notify_followers.label_tag }}
                    {{ post_create_form.notify_followers }}
                    <span class="helpText">{{ post_create_form.notify_followers.help_text }}</span>
                </div>

                <div class="checkbox">
                    <label for="id_track_votes">Track Votes:</label>
                    {{ poll_create_form.track_votes }}
                    <span class="helpText">
                        {{ poll_create_form.track_votes.help_text }}
                    </span>
                </div>

                {#            <input type="text" name="title" class="poll-question" placeholder="Enter The Poll Question" required>#}
                <br><br>

            {% if not edit %}

                <div style="font-weight: bolder; font-size: larger">Add options for your poll:</div>
                <p style="color:red;font-style: italic; font-weight: bold">Be Careful! Options once set can not be changed.</p>
                <br>
                <ul class="option-list">


                        <li>
                            <input type="text" name="0" placeholder="Write Your Option here!" required>
                        </li>
                        <li>
                            <input type="text" name="1" placeholder="Write Your Option here!" required>
                        </li>

                </ul>

                <div class="row justify-content-around">
                    <div class="col-lg-3">
                        <button id="add-option" class="add-option">Add Option Here</button>
                    </div>
                    <div class="col-lg-3 col-lg-offset-6">
                        <input class="poll-submit" type="submit" value="Submit">
                    </div>
                </div>
                <input name="hidden-count" class="option-count" type="hidden" value="2">
            {% else %}
                <div class="row">

                    <div class="col-lg-3 col-lg-offset-6">
                        <input class="poll-submit" type="submit" value="Submit">
                    </div>
                </div>
            {% endif %}
            </form>
        </div>

    </div>

    <script>
        {% if not edit %}
        let nameCounter = 1;
        document.querySelector('.add-option').addEventListener('click', function (e) {
            e.preventDefault();
            let liNode = document.createElement('li');
            let inputField = document.createElement('input');

            inputField.setAttribute("name", String(++nameCounter));
            inputField.setAttribute("placeholder", "Write Your Option here!");
            inputField.setAttribute("type", "text");
            inputField.required = true;

            liNode.appendChild(inputField);

            document.querySelector('.option-list').appendChild(liNode);

            // No of options
            document.querySelector('.option-count').value = nameCounter + 1;
        });

        {% endif %}

    </script>


{% endblock %}