accounts/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.views.generic import TemplateView
from . import calendar_views as calviews
app_name = "accounts"

urlpatterns = [
    path('change-password', views.change_password, name='password-change'),
    path('<slug:club_name>/list-for-president/', views.listForPresident, name='list_for_president'),
    path('<slug:club_name>/list-for-moderator/', views.listForModerator, name='list_for_moderator'),
    path('makeMember/', views.makeMember, name='make_member'),
    path('makeModerator/', views.makeModerator, name='make_moderator'),
    path('profile/', views.profile, name='profile'),

    # Calendar urls
    url(r'^calendar/next/(?P<select>\w+)/(?P<show>\w+)/$', calviews.date, name='date'),
    # path('next/<select>/',views.date,name = "date"),
    # path('back/<select>/',views.date1,name = "date1"),
    url(r'^calendar/back/(?P<select>\w+)/(?P<show>\w+)/$', calviews.date1, name='date1'),
    path('events_enter/<int:date_selected>', calviews.event_enter, name="event_enter"),
    url(r'^calendar/land/(?P<select>\w+)/(?P<show>\w+)/$', calviews.hello, name='index'),
    url(r'^calendar/choose/(?P<select>\w+)/(?P<show>\w+)/$', calviews.choose_event, name='choose'),
]

api/urls.py
from django.urls import path
from rest_framework_simplejwt import views as jwt_views

from api import views

app_name = 'api'

urlpatterns = [
    # Your URLs...
    path('token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('firebasetoken/', views.FirebaseTokenObtainPairView.as_view(), name='firebase_token_obtain_pair'),
    path('token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    path('test', views.HelloView.as_view(), name="hello"),
]

club_portal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from base import views as base_views

urlpatterns = [
    path('api/', include("api.urls")),
    path('admin/', admin.site.urls),
    path('registration/', include("registration.urls")),
    path('accounts/', include("accounts.urls")),
    path('posts/', include("posts.urls")),
    # path('', base_views.IndexView.as_view(), name="index"),
    path('', include("base.urls")),
    path('ckeditor/', include("ckeditor_uploader.urls")),
    path('', include('django.contrib.auth.urls')),
    path('random-useless-path/', include("posts.urls")),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import User
from django.db import models
from posts.models import Event


# Create your models here.
class Calendar(models.Model):
    date = models.DateField()
    work_title = models.CharField(max_length=34)
    user = models.ForeignKey(User, default='', on_delete=models.CASCADE)

    def __str__(self):
        return str(self.date) + ',' + str(self.work_title)

accounts/forms.py
from django import forms

from accounts.models import Calendar


class PasswordResetForm(forms.Form):
    old_password = forms.CharField(widget=forms.PasswordInput, required=False)
    new_password = forms.CharField(widget=forms.PasswordInput)
    new_password2 = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()

        if cleaned_data['new_password'] != cleaned_data['new_password2']:
            self.add_error('new_password2', 'Both Passwords do not match!')


MONTHS = (
    (1, 'January'),
    (2, 'February'),
    (3, 'March'),
    (4, 'April'),
    (5, 'May'),
    (6, 'June'),
    (7, 'July'),
    (8, 'August'),
    (9, 'September'),
    (10, 'October'),
    (11, 'November'),
    (12, 'December'),
)


class CalendarForm(forms.ModelForm):
    class Meta:
        model = Calendar
        fields = (
            'work_title',
        )


class ChooseMonthAndYearForm(forms.Form):
    month = forms.ChoiceField(choices=MONTHS)
    year = forms.ChoiceField(choices=[(x, x) for x in range(1950, 3000)], initial=2019)

accounts/views.py
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render, redirect, HttpResponse

from accounts.forms import PasswordResetForm
from base.models import ClubPresident, ClubModerator, Club, ClubMember
from django.contrib.auth.models import User

# Calendar imports

from django.shortcuts import render



def listForPresident(request, club_name):
    club = Club.objects.get(name=club_name)

    try:
        if club.clubpresident.user == request.user:
            moderators = club.clubmoderator_set.filter(is_approved=False)
        else:
            moderators = []
    except:
        moderators = []


    context = {
        'mods': moderators,
        'club_name': club_name
    }

    return render(request, 'accounts/listForPresident.html', context)


def listForModerator(request, club_name):
    club = Club.objects.get(name=club_name)
    try:
        club.clubmoderator_set.get(user=request.user)
        users = club.clubmember_set.filter(is_approved=False)
    except:
        users = []

    context = {
        'users': users,
        'club_name': club_name
    }

    return render(request, 'accounts/listForModerator.html', context)


def makeModerator(request):
    if request.method == 'POST':
        username = request.POST.get('username', None)
        club = request.POST.get('club_name', None)

        user = User.objects.get(username=username)
        club = Club.objects.get(name=club)

        new_member = ClubModerator.objects.get(user=user, club=club)
        new_member.is_approved = True
        new_member.save()

        data = {

        }

        return JsonResponse(data)


def makeMember(request):
    if request.method == 'POST':
        username = request.POST.get('username', None)
        club = request.POST.get('club_name', None)

        user = User.objects.get(username=username)
        club = Club.objects.get(name=club)

        new_member = ClubMember.objects.get(user=user, club=club)
        new_member.is_approved = True
        new_member.save()

        data = {

        }

        return JsonResponse(data)


def makeModerator(request):
    if request.method == 'POST':
        username = request.POST.get('username', None)
        club = request.POST.get('club_name', None)

        user = User.objects.get(username=username)
        club = Club.objects.get(name=club)

        new_member = ClubModerator.objects.get(user=user, club=club)
        new_member.is_approved = True
        new_member.save()

        data = {

        }

        return JsonResponse(data)


@login_required
def change_password(request):
    if request.method == "POST":
        password_reset_form = PasswordResetForm(request.POST)

        if password_reset_form.is_valid():
            if request.user.has_usable_password():
                if request.user.check_password(password_reset_form.cleaned_data['old_password']):
                    request.user.set_password(password_reset_form.cleaned_data['new_password'])
                    request.user.save()
                    login(request, request.user)
                    return redirect('accounts:profile')
                else:
                    password_reset_form.add_error('old_password', 'Incorrect Old Password')

            else:
                request.user.set_password(password_reset_form.cleaned_data['new_password'])
                request.user.save()
                login(request, request.user)
                return redirect('accounts:profile')
    else:
        password_reset_form = PasswordResetForm()

    return render(request, 'accounts/change_password.html', {'form': password_reset_form})


@login_required
def profile(request):
    context = {
        'posts': request.user.post_set.all(),
        # 'member_club': request.user.clubmember_set.all()
    }

    return render(request, 'accounts/profile.html', context)


# from first_app.forms import calendar_data
# Create your views here.
next_m = 0
next_y = 0
back_m = 0
back_y = 0

accounts/templates/accounts/put_templates/date.html
<!DOCTYPE html>
{% load staticfiles %}
{% load crispy_forms_tags %}

<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'calender_css/date.css' %}">


</head>
<body>
<div class="container">

    <div class="jumbotron" style="display:flex;flex-wrap:wrap;background:none;">

            {% if form  %}
            <div class="side-cal-1">
                &nbsp;
                <p>{{final_date}}<p>
                <p> Events:<p>
                {% for i in events %}
                    <p> {{ i.work_title }} </p>
                {% endfor %}
                <div class="container" style="margin-bottom: 50px;">
                    <form method="post">
                        {% csrf_token %}

                        <p>Add a event on this day:
                            <br>
                            {{ form.work_title }}<p>

                    <button type="submit">Create Event</button>
                    </form>
                 </div>

            </div>
             {% else %}

             <div class="side-cal-1">
                &nbsp;
                 <div>
                    <form action="{% url 'accounts:choose' select='1' show='1'%}" method="post">
                        {% csrf_token %}

                        <div class="event-input">
                            <label for="id_month">Month:</label>
                            {{ mandy.month }}
                        </div>

                        <div class="event-input">
                            <label for="id_year">Year:</label>
                            {{ mandy.year }}
                        </div>

                        <input type="submit" value="Check" class="btn btn-primary">
                    </form>
                </div>
             </div>



             {% endif %}
        <center class="side-cal-2">

            <main>

                <form action="{% url 'accounts:date' select='1' show='1'%}" method="post" style="position : relative;float : right;">
                    {% csrf_token %}
                    <input type="submit" value="next" class="btn btn-primary">
                </form>

                <form action="{% url 'accounts:date1' select='1' show='1' %}" method="post" style="position : relative;float:left;">
                    {% csrf_token %}
                    <input type="submit" value="back" class="btn btn-primary">
                </form>

                <h3>CALENDAR</h3>

                <div class="calendar">
                    <p>{{ present_year }}</p>
                    <div class="calendar__header">
                        <div>mon</div>
                        <div>tue</div>
                        <div>wed</div>
                        <div>thu</div>
                        <div>fri</div>
                        <div>sat</div>
                        <div>sun</div>
                    </div>


                    {% for i,j in zipped_data %}

                        <div class="calendar__week">
                            {% if i.0 == 0 %}
                                <div class="calendar__day day" data-toggle="modal" data-target="#myModal"></div>
                            {% else %}
                                {% if j.0 == 0 %}
                                <button type="button" class="btn btn-cal" onclick="location.href='{% url 'accounts:index' select=year_no  show=i.0 %}'" >{{ i.0 }}</button>
                                {% else %}
                                <button type="button" class="btn btn-cal" style="background-color: blue" onclick="location.href='{% url 'accounts:index' select=year_no  show=i.0 %}'" >{{ i.0 }}</button>

                                {% endif %}

                            {% endif %}


                            {% if i.1 == 0 %}
                                <div class="calendar__day day" data-toggle="modal" data-target="#myModal"></div>
                            {% else %}
                                {% if j.1 == 0 %}
                                <button type="button" class="btn btn-cal"  onclick="location.href='{% url 'accounts:index' select=year_no  show=i.1 %}'" >{{ i.1 }}</button>
                                {% else %}
                                <button type="button" class="btn btn-cal" style="background-color: blue" onclick="location.href='{% url 'accounts:index' select=year_no  show=i.1 %}'" >{{ i.1 }}</button>

                                {% endif %}


                            {% endif %}


                            {% if i.2 == 0 %}
                                <div class="calendar__day day" data-toggle="modal" data-target="#myModal"></div>
                            {% else %}
                                {% if j.2 == 0 %}
                                <button type="button" class="btn btn-cal" onclick="location.href='{% url 'accounts:index' select=year_no  show=i.2 %}'" >{{ i.2 }}</button>
                                {% else %}
                                <button type="button" class="btn btn-cal" style="background-color: blue" onclick="location.href='{% url 'accounts:index' select=year_no  show=i.2 %}'" >{{ i.2 }}</button>

                                {% endif %}


                            {% endif %}

                            {% if i.3 == 0 %}
                                <div class="calendar__day day" data-toggle="modal" data-target="#myModal"></div>
                            {% else %}
                                {% if j.3 == 0 %}
                                <button type="button" class="btn btn-cal" onclick="location.href='{% url 'accounts:index' select=year_no  show=i.3 %}'" >{{ i.3 }}</button>
                                {% else %}
                                <button type="button" class="btn btn-cal" style="background-color: blue" onclick="location.href='{% url 'accounts:index' select=year_no  show=i.3 %}'" >{{ i.3 }}</button>

                                {% endif %}

                            {% endif %}


                            {% if i.4 == 0 %}
                                <div class="calendar__day day" data-toggle="modal" data-target="#myModal"></div>
                            {% else %}
                                {% if j.4 == 0 %}
                                <button type="button" class="btn btn-cal" onclick="location.href='{% url 'accounts:index' select=year_no  show=i.4 %}'" >{{ i.4 }}</button>
                                {% else %}
                                <button type="button" class="btn btn-cal" style="background-color: blue" onclick="location.href='{% url 'accounts:index' select=year_no  show=i.4 %}'" >{{ i.4 }}</button>

                                {% endif %}

                            {% endif %}

                            {% if i.5 == 0 %}
                                <div class="calendar__day day" data-toggle="modal" data-target="#myModal"></div>
                            {% else %}
                                {% if j.5 == 0 %}
                                <button type="button" class="btn btn-cal" onclick="location.href='{% url 'accounts:index' select=year_no  show=i.5 %}'" >{{ i.5 }}</button>
                                {% else %}
                                <button type="button" class="btn btn-cal" style="background-color: blue" onclick="location.href='{% url 'accounts:index' select=year_no  show=i.5 %}'" >{{ i.5 }}</button>

                                {% endif %}

                            {% endif %}


                            {% if i.6 == 0 %}
                                <div class="calendar__day day" data-toggle="modal" data-target="#myModal"></div>
                            {% else %}
                                {% if j.6 == 0 %}
                                <button type="button" class="btn btn-cal" onclick="location.href='{% url 'accounts:index' select=year_no  show=i.6 %}'" >{{ i.6 }}</button>
                                {% else %}
                                <button type="button" class="btn btn-cal" style="background-color: blue" onclick="location.href='{% url 'accounts:index' select=year_no  show=i.6 %}'" >{{ i.6 }}</button>

                                {% endif %}

                            {% endif %}

                        </div>
                    {% endfor %}
                </div>

            </main>

        </center>
    </div>

</div>

</body>
</html>